### PR TITLE
Get role

### PR DESCRIPTION
**Pull request by QuicheLorraine3600**
This PR greatly simplifies the role management of the app.

As asked in #105, I replaced the ugly object ChimpagneRoles by a clean enum ChimpagneRole:
- ChimpagneRole.OWNER -> the user if the King Kong of the event
- ChimpagneRole.STAFF -> the user is in the event stafflist
- ChimpagneRole.GUEST -> the user is in the event guestlist
- CimpagneRole.NOT_IN_EVENT -> the user isn't in the event

On a ChimpagneEvent, you can now call the method getRole(ChimpagneAccountUID) to get the role of user, no need to check yourself the stafflist, guestlist and ownerId fields.

I also modified  ViewDetailedEventScreen to take a ChimpagneRole (instead of a boolean saying if the user can edit or not the event) to easily make the difference between the owner and a staff.

### CODE REVIEW

**Comment by QuicheLorraine3600** [comment]
Waiting for #123 to be merged to make the tests pass

**Review by juaniac — CHANGES_REQUESTED** [review]
Amazing refactoring!
These changes make it much easier manage the roles for participants of an event.
Good job on integrating new tests for the joining events, and updating older test that used a different system for role management.

Just one small change, is it really necessary to pass by argument the role of an user to the view details of event screen ? 
image

Since it is easy to find the role of a person, couldn't we just use the new getRole function inside the view details of events screen to determine which parts of the UI are available to the user.

Other than that small change I approve this PR.

**Comment by QuicheLorraine3600** [comment]
Indeed, it would be a better solution. However there is a small issue: ViewEventDetailScreen uses EventViewModel and this ViewModel doesn't store any reference a ChimpagneEvent. I could use buildChimpagneEvent and then use getRole on it BUT currently buildChimpagneEvent seems to assume it is the database job to provide the ownerId of the event and hence put this field to the empty string. 
This is a huge issue when editing an event for #108 so I'm opening a new PR soon to solve this issue.

**Comment by QuicheLorraine3600** [comment]
Requested changes addressed @juaniac  !

**Review by juaniac — APPROVED** [review]
Wonderful, this is perfection!
I approve this PR to be merged with main.

**Pull request merged**
