### PR TITLE
add Database and bases of ChimpagneEventManager

### PR DESCRIPTION
**Pull request by QuicheLorraine3600**
I created the bases of the ChimpagneEvent and ChimpagneEventManager class for our Database. The currently available method of ChimpagneEventManager are "getAllEvents", "getEventById", "updateEvent" and "deleteEvent".

### CODE REVIEW

**Review by juaniac — CHANGES_REQUESTED** [review]
Good work!
Try adding more attributes to events for the organisational process of an event like the list of participants, the car pooling list, the tags for an events. 
You can also already add filter functions to the data class ChimpagneEvent as well.

**Comment by QuicheLorraine3600** [comment]
> Good work! Try adding more attributes to events for the organisational process of an event like the list of participants, the car pooling list, the tags for an events. You can also already add filter functions to the data class ChimpagneEvent as well.

Car pooling isn't part of Sprint 2
I added all this stuff but its hard to test wether it's working or not without UI.

**Review by arnaudlvq — APPROVED** [review]
The cleanup of the list of dependencies is much appreciated (with newer versions)
Code seems well formatted
CRUD operations ok, missing Create ?

**Review by arnaudlvq — APPROVED** [review]
Seems like a PR duplicate

**Pull request merged**
