### PR TITLE
refactoring

### PR DESCRIPTION
**Pull request by Athanaze**
This PR adds comments and renames some functions according to Chimpagne's conventions.

### CODE REVIEW

**Comment by QuicheLorraine3600** [comment]
Where is the description ?

**Review by QuicheLorraine3600 — CHANGES_REQUESTED** [review]
I only noticed now: please improve your coverage, the whole app has currently only 82% of coverage, we can't accept PR lower than 80%.

**Review by QuicheLorraine3600 — APPROVED** [review]
image
SonarCloud is ridiculous, I approve this PR

**Review by juaniac — CHANGES_REQUESTED** [review]
Really appreciate the small and simple PR that helps for readability.

But this PR kinda missed some of the really non clear design choices we made:
- The biggest one is the use of the nullable event id argument in the EventViewModel, from an outsider it is difficult to know how it is managed without taking the time to see how the code works (and even some team members did too). So I believe that needs some documentation added.
 - The FindEventViewModel also needs documentation for the difference between the functions fetchEvents and fetchAroundLocation as it wasn't clear to me at first, so it will probably be the same for an outsider. Plus a renaming of the function fetchAroundLocation because it doesn't clearly describe what it does (as fetchEvents also fetches events around a location).

After applying these changes, this PR would have done its job of making the code more clear.

**Comment by Athanaze** [comment]
fetchAroundLocation is now called fetchFeedEvents
the behavior of the nullable event id is now explained

**Pull request merged**
