### PR TITLE
Supplies

### PR DESCRIPTION
**Pull request by Athanaze**
Adds the supplies functionnality in the event creation screen.
The data is immediately saved on firebase and displayed as a list.
When the event is created, the list with the IDs of supplies is set as attribute to the created event.
61.7 % line test coverage.

### CODE REVIEW

**Review by juaniac — CHANGES_REQUESTED** [review]
I believe this PR is not ready for review and as such it should be turn into a draft PR to avoid confusion.
The View Model integration is inexistent and most of the functions written are unused.

[Fixed] Converted to draft request

**Review by juaniac — CHANGES_REQUESTED** [review]
I really like the most of the things done here, but I still believe some changes are required:

On the UI side:
- The unit and quantity types for the supplies in the UI screen are quite small which makes them hard to read, especially with the light grey text color. So you should modify that.
- It would be nice to be able to remove a supply item while creating an event, you should add a "x" icon on the side which removes the selected supply from the list of supplies.

On the implementation:
- I don't believe it is the best idea to add to the database a supply each time the user decides to write one up. It would be better to have in the view model a list of event supplies to which you add / remove supplies to, and only once the user saves the event, the createTheEvent view model function registers each supply to the database, and upon completion registers the event. So the UI would not be the one to call the registerSupply and addSupplyToEvent functions as they would be called directly from within the view model. Thus these functions should be made private. If the user doesn't provide any supplies them nothing is called, and only the event is registered.
- The actual list of supplies should not be a var as that removes the purpose having a view model. Thus you also need add functions to update the list of supplies just like the other  parameters that the event view model has. 

On the tests:
- You should add tests for the new view model and database functions, this should get you past the 70% or maybe even 80% code coverage. You can take inspiration from the EventViewModelTests file to make your tests for the supplies part of the view model and database.

**Comment by Athanaze** [comment]
> I really like the most of the things done here, but I still believe some changes are required:
> 
> On the UI side:
> 
> * The unit and quantity types for the supplies in the UI screen are quite small which makes them hard to read, especially with the light grey text color. So you should modify that.
> * It would be nice to be able to remove a supply item while creating an event, you should add a "x" icon on the side which removes the selected supply from the list of supplies.
> 
> On the implementation:
> 
> * I don't believe it is the best idea to add to the database a supply each time the user decides to write one up. It would be better to have in the view model a list of event supplies to which you add / remove supplies to, and only once the user saves the event, the createTheEvent view model function registers each supply to the database, and upon completion registers the event. So the UI would not be the one to call the registerSupply and addSupplyToEvent functions as they would be called directly from within the view model. Thus these functions should be made private. If the user doesn't provide any supplies them nothing is called, and only the event is registered.
> * The actual list of supplies should not be a var as that removes the purpose having a view model. Thus you also need add functions to update the list of supplies just like the other  parameters that the event view model has.
> * When an event gets deleted from the database, all of the supplies created for that events should also be deleted for that event. You should add that functionality.
> 
> On the tests:
> 
> * You should add tests for the new view model and database functions, this should get you past the 70% or maybe even 80% code coverage. You can take inspiration from the EventViewModelTests file to make your tests for the supplies part of the view model and database.

The supplies are now added to the database only at event creation.
More tests have been added for the View model and ChimpagneSuppliesManager, achieving 86% line coverage 😎

**Review by juaniac — CHANGES_REQUESTED** [review]
Fantastic changes to the UI, it is much more user friendly. The tests are much more robust and varied. And I am glad you managed to implement most of the requested changes correctly!

But there are still some bizarre implementation choice which should be modified:
- You should not be modifying the event id in the register supply fucntions, so this should be deleted:
image
- In registerSupply these 2 lines should be swapped, since we use the loading parameter to know when the view model has finished updating their values:
image
- The event in the database doesn't store the any supply ids when created:
image
This is most certainly because you do not wait for the database to finish assigning the ids to the supplies in this part of the code for the UI:
image
 - Finally the supply list in the viewmodel must NOT be a var because it defeats the purpose of the mutable state flow of the data class for the viewmodel.
 To use a val, you need to create a function that takes as input a list a supply ids and copy it to the state of the view model. Here is an example for the location in the same viewmodel:
image
Then you can access the state outside the viewmodel using this line of code:
image.
- I believe that it should be the view model that keeps state on the actual list of supplies instead of the UI, so that we can know which supplies were already registered, which are in new and which were deleted (in the case of editing a pre-existing event).
- Upon deletion of an event, it should also delete the corresponding supplies for that event as well.
-  You should create a function that fetches all supplies for a pre-existing event in the view model.

**Comment by Athanaze** [comment]
The supply id is the document id, the same pattern used elsewhere in the app

**Comment by Athanaze** [comment]
"Upon deletion of an event, it should also delete the corresponding supplies for that event as well." 
image
What are you talking about ? This is already the case.

**Comment by juaniac** [comment]
Ah yes my bad.
Never the less the other changes must be made so that you follow our view model conventions!

**Comment by QuicheLorraine3600** [comment]
Can you use our View Model conventions ?
- Do not put var in EventUIState
- The temporary supply list should be stored in the View Model and not the UI directly
- The signature EventViewModel.registerSupply should be registerSupply(supply, onSuccess, onFailure) and not registerSupply(onSuccess, onFailure, supply)

**Review by arnaudlvq — COMMENTED** [review]
Great work on the supplies functionality for event creation !
The UI enhancements and ViewModel integration are well-executed. I recommend increasing the text size for supply details and prev and next buttons for better readability. **I adhere to immutability in the ViewModel by using val instead of var**. Also, consider refining the method signatures for clarity and consistency (EventManager -> EventsManager). The increased test coverage is impressive and contributes to a robust application.

**Comment by Athanaze** [comment]
"Also, consider refining the method signatures for clarity and consistency (EventManager -> EventsManager)"
I don't think this kind of refactoring is suited for this PR. It touches many files already.

**Review by juaniac — CHANGES_REQUESTED** [review]
Alright! This is almost perfect, there are still things to modify before merging to main:
- Biggest issue is that when we load an existing Event we have no way to differentiate between an already pre-existing supply (one that is on the database) and one that is has been added temporally using the UI while editing the event. This is an issue because if the user deletes a supply that is also in the database we should also delete it in the database. So you need to have a way a differentiate between a supply that is on the database so that once it is removed you can delete from the database. You can make the ids for supplies nullable so that a supply that has a null id is a temporary supply and a supply that has a string id is one that is already on the database. This means that you have to add a delete function to the view model which removes a particular supply, and checks if the id is null. For consistent sake you can also add an addSupply supply function that does the opposite.
- I don't understand point of having the msupplieslist as a data argument since it is almost exclusively used inside the viewmodel. The only time it is used outside is in the UI:
image
But this inclusion doesn't make sense to me, once we finish registering all events, the value of both supply list will be the same so I do not understand the logic of updating it to the same value. Maybe the logic is that since you implemented the update to also put the loading to false, the call to update isn't for changing the supplies but to put the loading to false ? If that is the case you can simply change the value of loading to false inside the view model after registering all supplies, instead of going about it in an round-about way.
 - I will yet again point out this error: 
image
What you are doing is changing the view model's state id, which corresponds the event's id and NOT the supply id, so overwriting it is not correct.
- I also do believe that it shouldn't be the UI that needs to call the register supplies, as it can done inside the view model just before creating the event. The UI only calls createTheEvent and then it is its job to register the supplies. This also removes copy paste code when the view model will be used for other UI screens.
 - Also remove all debugging tools before re-asking a PR such as prints.
 - Finally try to fix all merge errors before asking for a review so that we can review the merge you done to see if it is correctly done.

**Comment by Athanaze** [comment]
"Finally try to fix all merge errors before asking for a review so that we can review the merge you done to see if it is correctly done.
Merge state
" The merge conflict happened afterward, look at the historic. At the last commit of this PR they were no conflicts.

**Comment by Athanaze** [comment]
"This is an issue because if the user deletes a supply that is also in the database we should also delete it in the database. So you need to have a way a differentiate between a supply that is on the database so that once it is removed you can delete from the database. " This will be for another PR, as this is irrelevant for this user story. Indeed, the user can already delete supplies in the event creation screen.

**Comment by juaniac** [comment]
Fine, I will do my own PR to refactor your code to be able to edit the supply list.
Just please fix the merge conflicts.

**Comment by QuicheLorraine3600** [comment]
See #103

**Pull request closed without merging**
